config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # restaurant index
  resources :restaurants, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: (0..5) }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
    @review = Review.new
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Restaurants</a>
      <ul>
        <li class="nav-item">
          <a class="nav-link" href="/restaurants/new">Create a restaurant</a>
        </li>
        <li>
          <a class="nav-link" href="/restaurants">All restaurants</a>
        </li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.label :category %>
  <p>must be one of the following: chinese, japanese, french, belgian, italian</p>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h2>These are all restaurants</h2>
<br>
<% @restaurants.each do |restaurant| %>
<h4><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h4>
<% end %>

app/views/restaurants/new.html.erb
<h2>Create a new restaurant</h2>
<br>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<br>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>


<%= link_to "All restaurants", restaurants_path %>
<br>
<br>
<h6>Reviews for this restaurant:</h6>
<% @restaurant.reviews.each do |review| %>
  <h3><%= review.rating %></h3>
  <p><%= review.content %></p>
<% end %>


<h2>Write a review</h2>
<br>
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<h2>Write a review</h2>
<br>
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<%= end %>